# Generated by Django 2.1.4 on 2019-12-09 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=99, verbose_name='事项')),
                ('flag', models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, max_length=1, verbose_name='标记')),
                ('add_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
