# Generated by Django 2.1.4 on 2019-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20191209_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
